"""task has no name

Revision ID: 2e65ed2861aa
Revises: 65ee0d8a4aad
Create Date: 2024-07-21 12:24:28.364286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e65ed2861aa'
down_revision: Union[str, None] = '65ee0d8a4aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
