"""fix PowerOfAttorney foreign key relationships

Revision ID: 2ff176c19909
Revises: 89f0f96e6c42
Create Date: 2024-07-22 02:06:42.069008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff176c19909'
down_revision: Union[str, None] = '89f0f96e6c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
