"""userRole

Revision ID: 327a69d42710
Revises: 6fb71c17e592
Create Date: 2024-07-22 04:46:35.403117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '327a69d42710'
down_revision: Union[str, None] = '6fb71c17e592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'author_role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('SUPPLIER', 'EXECUTOR', 'SUPERVISOR', 'GUEST', name='userrole'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'author_role',
               existing_type=sa.Enum('SUPPLIER', 'EXECUTOR', 'SUPERVISOR', 'GUEST', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
