"""tasks fix

Revision ID: 4a8902dba4ba
Revises: f019cf7df854
Create Date: 2024-07-20 12:09:55.246701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a8902dba4ba'
down_revision: Union[str, None] = 'f019cf7df854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'executor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('tasks', 'executor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
