"""task date type fix

Revision ID: 53d2d46d992e
Revises: 6c87b96b72d6
Create Date: 2024-08-21 11:06:33.330081

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53d2d46d992e'
down_revision: Union[str, None] = '6c87b96b72d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'type',
                    existing_type=mysql.ENUM('error', 'comment', 'status_change',
                                             'date_change', 'user_change', 'notified'),
                    type_=mysql.ENUM('error', 'comment', 'status_change', 'date_change',
                                     'user_change', 'notify_sent', 'notified'),
                    existing_nullable=True,
                    nullable=False)
    op.alter_column('tasks', 'initial_plan_date',
                    existing_type=mysql.DATETIME(),
                    type_=sa.Date(),
                    existing_nullable=False)
    op.alter_column('tasks', 'actual_plan_date',
                    existing_type=mysql.DATETIME(),
                    type_=sa.Date(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'actual_plan_date',
                    existing_type=sa.Date(),
                    type_=mysql.DATETIME(),
                    existing_nullable=False)
    op.alter_column('tasks', 'initial_plan_date',
                    existing_type=sa.Date(),
                    type_=mysql.DATETIME(),
                    existing_nullable=False)
    op.alter_column(
        'comments',
        'type',
        existing_type=mysql.ENUM('error', 'comment', 'status_change', 'date_change', 'user_change', 'notify_sent',
                                 'notified'),
        type_=mysql.ENUM('error', 'comment', 'status_change', 'date_change', 'user_change', 'notified'),
        existing_nullable=False,
        nullable=False
    )
