"""fix relationships to use list of documents

Revision ID: 6fb71c17e592
Revises: 2ff176c19909
Create Date: 2024-07-22 02:13:05.695274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6fb71c17e592'
down_revision: Union[str, None] = '2ff176c19909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('power_of_attorneys_ibfk_1', 'power_of_attorneys', type_='foreignkey')
    op.drop_column('power_of_attorneys', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_of_attorneys', sa.Column('document_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('power_of_attorneys_ibfk_1', 'power_of_attorneys', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
