"""document relationships fix

Revision ID: 89f0f96e6c42
Revises: 2e65ed2861aa
Create Date: 2024-07-22 01:56:13.162784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89f0f96e6c42'
down_revision: Union[str, None] = '2e65ed2861aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_document_comment_links')
    op.add_column('documents', sa.Column('comment_id', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('power_of_attorney_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'comments', ['comment_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'power_of_attorneys', ['power_of_attorney_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'power_of_attorney_id')
    op.drop_column('documents', 'comment_id')
    op.create_table('task_document_comment_links',
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('document_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='task_document_comment_links_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='task_document_comment_links_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_document_comment_links_ibfk_3', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'document_id', 'comment_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
