"""document delete

Revision ID: aa2ab52c6ce5
Revises: 72b59ecbea76
Create Date: 2024-08-02 00:34:07.588270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2ab52c6ce5'
down_revision: Union[str, None] = '72b59ecbea76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'deleted')
    # ### end Alembic commands ###
