"""notification deletion control flag

Revision ID: bc3f23288e1d
Revises: 1466ddb9579a
Create Date: 2024-08-19 00:38:08.708591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3f23288e1d'
down_revision: Union[str, None] = '1466ddb9579a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_notifications', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_notifications', 'active')
    # ### end Alembic commands ###
