"""unnecessary email fix

Revision ID: e86da2617b3d
Revises: eb71614ea35c
Create Date: 2024-07-23 10:27:33.957189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86da2617b3d'
down_revision: Union[str, None] = 'eb71614ea35c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
