"""references active flag

Revision ID: f019cf7df854
Revises: 234df2616642
Create Date: 2024-07-07 15:51:06.008844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f019cf7df854'
down_revision: Union[str, None] = '234df2616642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('organizations', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'active')
    op.drop_column('objects', 'active')
    # ### end Alembic commands ###
